pipeline:
  test:
    image: clojure
    commands:
      - lein test

  build:
    image: clojure
    commands:
      - lein uberjar

  docker:
    image: plugins/docker
    repo: uswitch/blueshift
    tags:
      - "${DRONE_COMMIT_SHA:0:8}"
